### PR TITLE
Added age workflow to parent submission form.  Added validation to pa…

### PR DESCRIPTION
**Pull request by Evilnames**
…rent submission form.  Added AVG AGE on the dashboard of events.

### CODE REVIEW

**Comment by tjhorner** [comment]
Testing locally, it seems that event pages die when there are no attendees. Add checks in your `getAvgAgeAttribute` function to make sure that there's at least 1 attendee before calculating it.

image

You also might want to change that line to `event.avg_age` to be consistent with the rest of the page.

**Comment by tjhorner** [comment]
Alright, should be fixed now. (There were some other commits on our copy of Clear internally so those will be merged as well)

Waiting for confirmation from @tylermenezes

**Comment by Evilnames** [comment]
Thanks for catching that.  I dunno how to add myself to another event to check the null situation.

**Comment by tylermenezes** [comment]
Thank you @Evilnames and @tjhorner!

**Pull request merged**
